

services:
  frontend:
    build:
      context: ./Frontend/paper-registration
    ports:
      - "4200:80"   
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
    ports:
      - "3000:3000"   
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=paper_registration
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: paper_registration
      MYSQL_PASSWORD: example
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data:
