services:
  frontend:
    build:
      context: .
      dockerfile: ./Frontend/paper-registration/Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./Backend/Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=paper_db
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: paper_db
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  app-network: {}

volumes:
  mysql-data: {}
