
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.prod 
    ports:
      - "4100:80" 
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NODE_ENV=production 
    restart: always

  backend:
    build:
      context: ./Backend
      
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local