name: Build and Test Docker Compose

# Trigger on push and pull request to main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Build Frontend
      - name: Build Frontend
        run: docker build -f ./Frontend/Dockerfile -t frontend-image:latest ./Frontend

      # Build Backend
      - name: Build Backend
        run: docker build -f ./Backend/Dockerfile -t backend-image:latest ./Backend
