name: Build and Test Docker Compose

# Trigger on push and pull request to main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/2.5.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Start Docker Compose
      - name: Start Docker Compose
        run: docker-compose -f ./docker-compose.yml up -d

      # Run any tests here (if you have test scripts or commands)
      - name: Run tests
        run: |
          # Example: Run Angular frontend tests
          docker-compose exec frontend npm test
          # Example: Run backend tests
          docker-compose exec backend npm test

      # Shut down the Docker Compose services
      - name: Stop Docker Compose
        run: docker-compose -f ./docker-compose.yml down
